// 军官/学院配置种子：数据源自 stzb-fk inithebing.sql（cfg_general / cfg_skill / cfg_equipment）

package seed

import "qqjiayuan/server/internal/model"

var ezfyEzfyCfgGeneral = []model.EzfyCfgGeneral{
	{ID: 1, Name: "Stalin（斯大林）", Level: 150, Military: 305, Logistics: 150, Learning: 200, Star: 5, Source: "300充值凭证+15万砖石", GetCondition: "505", Skill: "活动中心换取", Des: "全技能+2，攻击+20％，出兵+20％", Recruit: 1},
	{ID: 2, Name: "Churchill（丘吉尔）", Level: 140, Military: 85, Logistics: 336, Learning: 118, Star: 5, Source: "6万砖石", GetCondition: "203", Skill: "商店买", Des: "", Recruit: 1},
	{ID: 3, Name: "阿诺德（Henry H Arnold）", Level: 140, Military: 145, Logistics: 56, Learning: 230, Star: 5, Source: "5万砖石", GetCondition: "375", Skill: "商店买", Des: "攻击防御速度+10％，英雄突击+2", Recruit: 1},
	{ID: 4, Name: "邓尼茨（Donitz）", Level: 140, Military: 190, Logistics: 120, Learning: 120, Star: 5, Source: "10套地图+15亿金+10万潜艇送35％战列生命章", GetCondition: "310", Skill: "任务（soul of wolf）", Des: "", Recruit: 1},
	{ID: 5, Name: "戴高乐（Charles）", Level: 140, Military: 230, Logistics: 70, Learning: 80, Star: 5, Source: "15亿金子", GetCondition: "310", Skill: "任务", Des: "", Recruit: 1},
	{ID: 6, Name: "White Beard", Level: 150, Military: 264, Logistics: 113, Learning: 201, Star: 5, Source: "10万砖石", GetCondition: "465", Skill: "商店购买", Des: "英雄突击+2，攻速移速+20％", Recruit: 1},
	{ID: 7, Name: "Maple", Level: 150, Military: 85, Logistics: 95, Learning: 295, Star: 5, Source: "5万砖石", GetCondition: "380", Skill: "商店购买", Des: "", Recruit: 1},
	{ID: 8, Name: "Guisan", Level: 140, Military: 250, Logistics: 102, Learning: 95, Star: 5, Source: "120个hero shards（刷野掉落）", GetCondition: "345", Skill: "刷野", Des: "", Recruit: 1},
	{ID: 9, Name: "巴顿（Patton）", Level: 130, Military: 220, Logistics: 60, Learning: 90, Star: 5, Source: "10亿金子", GetCondition: "310", Skill: "任务", Des: "陆军生命，攻击+15％", Recruit: 1},
	{ID: 10, Name: "朱可夫（Zhukov）", Level: 130, Military: 220, Logistics: 60, Learning: 90, Star: 5, Source: "10亿金子", GetCondition: "310", Skill: "任务", Des: "", Recruit: 1},
	{ID: 11, Name: "隆美尔（Rommel）", Level: 130, Military: 215, Logistics: 100, Learning: 55, Star: 5, Source: "10亿金子", GetCondition: "270", Skill: "任务", Des: "", Recruit: 1},
	{ID: 12, Name: "崔可夫（Chuikov）", Level: 120, Military: 230, Logistics: 95, Learning: 105, Star: 5, Source: "10亿金子", GetCondition: "335", Skill: "任务", Des: "反击+2，生命+15％，出兵+20％", Recruit: 1},
	{ID: 13, Name: "蒋介石（Chiang Kai-shek）", Level: 140, Military: 60, Logistics: 90, Learning: 230, Star: 5, Source: "15亿金子", GetCondition: "290", Skill: "任务", Des: "", Recruit: 1},
	{ID: 14, Name: "史迪威（Stilwell）", Level: 130, Military: 85, Logistics: 95, Learning: 255, Star: 5, Source: "100充值凭证", GetCondition: "340", Skill: "任务", Des: "", Recruit: 1},
	{ID: 15, Name: "马歇尔（Marshall）", Level: 130, Military: 120, Logistics: 245, Learning: 80, Star: 5, Source: "50充值凭证", GetCondition: "200", Skill: "任务", Des: "油耗+2，后勤+300，训练时间-15％", Recruit: 1},
	{ID: 16, Name: "天皇（Emperor Showa）", Level: 140, Military: 60, Logistics: 230, Learning: 90, Star: 5, Source: "15亿金子", GetCondition: "150", Skill: "任务", Des: "", Recruit: 1},
	{ID: 17, Name: "赫鲁晓夫（Khrushchev）", Level: 130, Military: 70, Logistics: 210, Learning: 90, Star: 5, Source: "10亿金子", GetCondition: "160", Skill: "任务", Des: "", Recruit: 1},
	{ID: 18, Name: "朱可夫（Zhukov）", Level: 130, Military: 220, Logistics: 60, Learning: 90, Star: 5, Source: "10亿金子", GetCondition: "310", Skill: "任务", Des: "突击+2，军事+300，攻速+30％", Recruit: 1},
	{ID: 19, Name: "科涅夫（Konev）", Level: 130, Military: 130, Logistics: 215, Learning: 66, Star: 5, Source: "15凭证", GetCondition: "196", Skill: "任务", Des: "", Recruit: 1},
	{ID: 20, Name: "罗科索夫斯基（Rokossovsky）", Level: 130, Military: 130, Logistics: 94, Learning: 70, Star: 5, Source: "15凭证", GetCondition: "200", Skill: "任务", Des: "", Recruit: 1},
	{ID: 21, Name: "麦克阿瑟（MacArthur）", Level: 130, Military: 210, Logistics: 110, Learning: 50, Star: 5, Source: "10亿金子", GetCondition: "260", Skill: "任务", Des: "防御+2，攻击防御+15％", Recruit: 1},
	{ID: 22, Name: "蒙哥马利（Montgomery）", Level: 130, Military: 210, Logistics: 75, Learning: 75, Star: 5, Source: "10亿金子", GetCondition: "285", Skill: "任务", Des: "", Recruit: 1},
	{ID: 23, Name: "爱森豪威尔（Eisenhower）", Level: 110, Military: 190, Logistics: 120, Learning: 60, Star: 5, Source: "110个Birthday Token（商店买）", GetCondition: "250", Skill: "任务", Des: "", Recruit: 1},
	{ID: 24, Name: "Model（莫德尔）", Level: 130, Military: 100, Logistics: 70, Learning: 200, Star: 5, Source: "100个Birthday Token（商店买）", GetCondition: "300", Skill: "任务", Des: "突击+2，攻速移速+15％", Recruit: 1},
	{ID: 25, Name: "古德里安（Guderian）", Level: 120, Military: 250, Logistics: 50, Learning: 80, Star: 5, Source: "110个Birthday Token（商店买）", GetCondition: "230", Skill: "任务", Des: "", Recruit: 1},
	{ID: 26, Name: "Portal（波特尔）", Level: 140, Military: 285, Logistics: 66, Learning: 105, Star: 5, Source: "15万砖石打包带走三个", GetCondition: "390", Skill: "商店购买", Des: "英雄突击+3，减少敌方核飞速度10%", Recruit: 1},
	{ID: 27, Name: "Gamelin（加木林）", Level: 140, Military: 95, Logistics: 70, Learning: 263, Star: 5, Source: "", GetCondition: "358", Skill: "", Des: "", Recruit: 1},
	{ID: 28, Name: "Darlin（达尔郎）", Level: 140, Military: 87, Logistics: 264, Learning: 101, Star: 5, Source: "", GetCondition: "188", Skill: "", Des: "", Recruit: 1},
	{ID: 29, Name: "Nimitz（尼米兹）", Level: 150, Military: 335, Logistics: 200, Learning: 250, Star: 5, Source: "600凭证+25万砖", GetCondition: "535", Skill: "活动中心兑换", Des: "一级：全技能+2\n二级：全技能+3，军队移速+20％，攻击+25％", Recruit: 1},
	{ID: 30, Name: "Clark（克拉克）", Level: 150, Military: 210, Logistics: 225, Learning: 300, Star: 5, Source: "10万砖石或者一定活跃凭证兑换", GetCondition: "510", Skill: "商店，任务", Des: "", Recruit: 1},
	{ID: 31, Name: "Bradley（布兰得利）", Level: 150, Military: 220, Logistics: 300, Learning: 215, Star: 5, Source: "10万砖石", GetCondition: "435", Skill: "商店买", Des: "", Recruit: 1},
}

var ezfyEzfyCfgSkill = []model.EzfyCfgSkill{
	{ID: 1, Name: "尖兵突击", Effect: "攻击力+30%", Type: 1,
		Des: "所有兵种、不含城防。擅于率领部队作为尖兵，突击敌方薄弱地带直接将敌人置于死地，效果与军官能力成正比，每3回合提升攻击力，持续1回合。可提升军官攻击力30%；"},
	{ID: 2, Name: "弧形防御", Effect: "防御力+30%", Type: 2,
		Des: "所有兵种、不含城防。经过严格训练所形成一种以军官为指挥核心的防御队列，效果与军官能力成正比，每3回合提升防御力，持续1回合。增加军官防御力30%；"},
	{ID: 3, Name: "绝地反击", Effect: "第1回合反击", Type: 2,
		Des: "所有兵种、不含城防。能够在被动挨打时机敏地发现敌人的进攻漏洞，并予以还击，不论率领任何部队均可在第1回合进行反击；"},
	{ID: 4, Name: "火炮控制", Effect: "陆军装甲攻击+10", Type: 1,
		Des: "所有地面装甲部队。可通过侦察确定目标的位置和运动规律，每3回合提升陆军装甲部队攻击，持续1回合。提升攻击力10；"},
	{ID: 5, Name: "坦克突袭", Effect: "陆军速度+10%", Type: 3,
		Des: "提升陆军速度，生效回合数随技能等级变化；"},
	{ID: 6, Name: "四指编队", Effect: "空军对空攻击+15%", Type: 1,
		Des: "提升空军对空攻击，生效回合数随技能等级变化；"},
	{ID: 7, Name: "闪电袭击", Effect: "空军速度+10%", Type: 3,
		Des: "提升空军速度，生效回合数随技能等级变化；"},
	{ID: 8, Name: "狼群战术", Effect: "海军对海攻击+15%", Type: 1,
		Des: "提高海军对海攻击，生效回合数随技能等级变化；"},
	{ID: 9, Name: "越岛战术", Effect: "海军速度+10%", Type: 3,
		Des: "提高海军速度，生效回合数随技能等级变化；"},
	{ID: 10, Name: "弹幕支援", Effect: "城防攻击范围+10%", Type: 2,
		Des: "提高城防攻击范围，生效回合数随技能等级变化；"},
	{ID: 11, Name: "黄金眼", Effect: "侦查等级+1", Type: 3,
		Des: "提高侦查等级，生效回合数随技能等级变化；"},
	{ID: 12, Name: "机械改造", Effect: "回收率+10%, 出征油耗-10%", Type: 3,
		Des: "增加回收率，减少出征油耗。"},
}

var ezfyEzfyCfgEquipment = []model.EzfyCfgEquipment{
	{ID: 1, Name: "青铜军刀", Type: "武器", Tier: 1, Military: 10, Logistics: 0, Learning: 0, Level: 10, Des: "初级武器,军事+10"},
	{ID: 2, Name: "步枪M1903", Type: "武器", Tier: 1, Military: 15, Logistics: 5, Learning: 0, Level: 15, Des: "初级武器,军事+15"},
	{ID: 3, Name: "钢盔", Type: "防具", Tier: 1, Military: 0, Logistics: 0, Learning: 10, Level: 10, Des: "初级防具,学识+10"},
	{ID: 4, Name: "军靴", Type: "防具", Tier: 1, Military: 0, Logistics: 10, Learning: 0, Level: 10, Des: "初级防具,后勤+10"},
	{ID: 5, Name: "望远镜", Type: "饰品", Tier: 1, Military: 5, Logistics: 5, Learning: 5, Level: 20, Des: "初级饰品,三属性+5"},
	{ID: 6, Name: "毛瑟手枪", Type: "武器", Tier: 2, Military: 30, Logistics: 0, Learning: 0, Level: 30, Des: "中级武器,军事+30"},
	{ID: 7, Name: "冲锋枪MP40", Type: "武器", Tier: 2, Military: 40, Logistics: 10, Learning: 0, Level: 40, Des: "中级武器,军事+40"},
	{ID: 8, Name: "防弹衣", Type: "防具", Tier: 2, Military: 0, Logistics: 0, Learning: 30, Level: 30, Des: "中级防具,学识+30"},
	{ID: 9, Name: "战术地图", Type: "饰品", Tier: 2, Military: 10, Logistics: 20, Learning: 20, Level: 35, Des: "中级饰品,后勤学识+20"},
	{ID: 10, Name: "勋章", Type: "饰品", Tier: 2, Military: 20, Logistics: 20, Learning: 20, Level: 40, Des: "中级饰品,三属性+20"},
	{ID: 11, Name: "狙击步枪", Type: "武器", Tier: 3, Military: 60, Logistics: 10, Learning: 10, Level: 50, Des: "高级武器,军事+60"},
	{ID: 12, Name: "合金装甲", Type: "防具", Tier: 3, Military: 10, Logistics: 0, Learning: 60, Level: 55, Des: "高级防具,学识+60"},
	{ID: 13, Name: "参谋指北针", Type: "饰品", Tier: 3, Military: 30, Logistics: 40, Learning: 40, Level: 60, Des: "高级饰品,后勤学识+40"},
	{ID: 14, Name: "战地电台", Type: "饰品", Tier: 3, Military: 40, Logistics: 40, Learning: 40, Level: 60, Des: "高级饰品,三属性+40"},
	{ID: 15, Name: "元帅权杖", Type: "武器", Tier: 4, Military: 120, Logistics: 30, Learning: 30, Level: 70, Des: "特殊武器,军事+120"},
	{ID: 16, Name: "元帅礼服", Type: "防具", Tier: 4, Military: 30, Logistics: 30, Learning: 120, Level: 75, Des: "特殊防具,学识+120"},
	{ID: 17, Name: "帝国勋章", Type: "饰品", Tier: 4, Military: 80, Logistics: 80, Learning: 80, Level: 80, Des: "特殊饰品,三属性+80"},
	{ID: 18, Name: "金质怀表", Type: "饰品", Tier: 4, Military: 50, Logistics: 100, Learning: 100, Level: 80, Des: "特殊饰品,后勤学识+100"},
	{ID: 19, Name: "红宝石", Type: "珠宝", Tier: 1, Military: 5, Logistics: 5, Learning: 5, Level: 1, Des: "珠宝(平原),三属性+5"},
	{ID: 20, Name: "蓝宝石", Type: "珠宝", Tier: 1, Military: 5, Logistics: 5, Learning: 5, Level: 1, Des: "珠宝(丘陵),三属性+5"},
	{ID: 21, Name: "绿宝石", Type: "珠宝", Tier: 1, Military: 5, Logistics: 5, Learning: 5, Level: 1, Des: "珠宝(森林),三属性+5"},
	{ID: 22, Name: "翡翠", Type: "珠宝", Tier: 1, Military: 5, Logistics: 5, Learning: 5, Level: 1, Des: "珠宝(草原),三属性+5"},
	{ID: 23, Name: "紫水晶", Type: "珠宝", Tier: 1, Military: 5, Logistics: 5, Learning: 5, Level: 1, Des: "珠宝(沼泽),三属性+5"},
	{ID: 24, Name: "猫眼石", Type: "珠宝", Tier: 1, Military: 5, Logistics: 5, Learning: 5, Level: 1, Des: "珠宝(盆地),三属性+5"},
	{ID: 25, Name: "玛瑙", Type: "珠宝", Tier: 1, Military: 5, Logistics: 5, Learning: 5, Level: 1, Des: "珠宝(山地),三属性+5"},
	{ID: 26, Name: "珍珠", Type: "珠宝", Tier: 1, Military: 5, Logistics: 5, Learning: 5, Level: 1, Des: "珠宝(海洋),三属性+5"},
}
